import type { Product, Category, BlogPost } from '@/types'

// ΓöÇΓöÇΓöÇ Categories ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Oral Compounds',
    slug: 'oral-compounds',
    description: 'Premium oral performance supplements',
    image_url: 'https://steroids-uk.com/wp-content/uploads/2022/03/kamagra-effervescent-100mg-tablets-1-500x500-1-300x300.webp',
    product_count: 24,
    children: [
      { id: 'cat-1-1', name: 'Strength Tablets', slug: 'strength-tablets', parent_id: 'cat-1', product_count: 8 },
      { id: 'cat-1-2', name: 'Recovery Tabs', slug: 'recovery-tabs', parent_id: 'cat-1', product_count: 6 },
      { id: 'cat-1-3', name: 'Lean Mass Oral', slug: 'lean-mass-oral', parent_id: 'cat-1', product_count: 5 },
      { id: 'cat-1-4', name: 'PCT Tablets', slug: 'pct-tablets', parent_id: 'cat-1', product_count: 5 },
    ],
  },
  {
    id: 'cat-2',
    name: 'Injectable Solutions',
    slug: 'injectable-solutions',
    description: 'Professional-grade injectable formulations',
    image_url: 'https://steroids-uk.com/wp-content/uploads/2017/11/Super-Kamagra-300x300.webp',
    product_count: 38,
    children: [
      { id: 'cat-2-1', name: 'Test Enanthate', slug: 'test-enanthate', parent_id: 'cat-2', product_count: 10 },
      { id: 'cat-2-2', name: 'Test Cypionate', slug: 'test-cypionate', parent_id: 'cat-2', product_count: 8 },
      { id: 'cat-2-3', name: 'Tren Series', slug: 'tren-series', parent_id: 'cat-2', product_count: 7 },
      { id: 'cat-2-4', name: 'Blend Formulas', slug: 'blend-formulas', parent_id: 'cat-2', product_count: 6 },
      { id: 'cat-2-5', name: 'Deca & NPP', slug: 'deca-npp', parent_id: 'cat-2', product_count: 7 },
    ],
  },
  {
    id: 'cat-3',
    name: 'Fat Burners',
    slug: 'fat-burners',
    description: 'Advanced thermogenic and metabolic boosters',
    image_url: 'https://steroids-uk.com/wp-content/uploads/2026/01/cialis-300x300.webp',
    product_count: 12,
    children: [
      { id: 'cat-3-1', name: 'Thermogenics', slug: 'thermogenics', parent_id: 'cat-3', product_count: 5 },
      { id: 'cat-3-2', name: 'Metabolic Support', slug: 'metabolic-support', parent_id: 'cat-3', product_count: 4 },
      { id: 'cat-3-3', name: 'GLP-1 Peptides', slug: 'glp1-peptides', parent_id: 'cat-3', product_count: 3 },
    ],
  },
  {
    id: 'cat-4',
    name: 'SARMs',
    slug: 'sarms',
    description: 'Selective androgen receptor modulators',
    image_url: 'https://steroids-uk.com/wp-content/uploads/2025/11/prilimed-30_blister-300x300.webp',
    product_count: 18,
    children: [
      { id: 'cat-4-1', name: 'Bulking SARMs', slug: 'bulking-sarms', parent_id: 'cat-4', product_count: 6 },
      { id: 'cat-4-2', name: 'Cutting SARMs', slug: 'cutting-sarms', parent_id: 'cat-4', product_count: 5 },
      { id: 'cat-4-3', name: 'Recomp SARMs', slug: 'recomp-sarms', parent_id: 'cat-4', product_count: 4 },
      { id: 'cat-4-4', name: 'SARMs Stacks', slug: 'sarms-stacks', parent_id: 'cat-4', product_count: 3 },
    ],
  },
  {
    id: 'cat-5',
    name: 'PCT & Support',
    slug: 'pct-support',
    description: 'Post-cycle therapy and ancillary support',
    image_url: 'https://steroids-uk.com/wp-content/uploads/2023/01/b-lgd-4033-ligandrol-pharmaqo-300x300.webp',
    product_count: 15,
    children: [
      { id: 'cat-5-1', name: 'Post Cycle Therapy', slug: 'post-cycle-therapy', parent_id: 'cat-5', product_count: 6 },
      { id: 'cat-5-2', name: 'Estrogen Control', slug: 'estrogen-control', parent_id: 'cat-5', product_count: 5 },
      { id: 'cat-5-3', name: 'Liver Support', slug: 'liver-support', parent_id: 'cat-5', product_count: 4 },
    ],
  },
  {
    id: 'cat-6',
    name: 'HGH & Peptides',
    slug: 'hgh-peptides',
    description: 'Growth hormone and research peptides',
    image_url: 'https://steroids-uk.com/wp-content/uploads/2020/08/imusclesarmsuk-ligandrollgd4033_1024x1024@2x-1-300x300.webp',
    product_count: 10,
  },
  {
    id: 'cat-7',
    name: 'Pre-Made Stacks',
    slug: 'pre-made-stacks',
    description: 'Expertly formulated combination packages',
    image_url: 'https://steroids-uk.com/wp-content/uploads/2024/05/Proscalpin-1-agm22mL-150x150.webp',
    product_count: 8,
  },
  {
    id: 'cat-8',
    name: 'Sexual Wellness',
    slug: 'sexual-wellness',
    description: 'Performance and vitality products',
    image_url: 'https://steroids-uk.com/wp-content/uploads/2024/02/finax_1mg_tablet_30s_35081_0_1-300x300.webp',
    product_count: 7,
  },
]

// ΓöÇΓöÇΓöÇ Products ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Testosterone-E 300 ΓÇô Pharmaqo Labs',
    slug: 'testosterone-enanthate-300',
    short_description: 'Long-acting testosterone ester. 300mg/ml ┬╖ 10ml vial.',
    description: 'Testosterone Enanthate 300 is a long-acting testosterone ester designed for sustained release over 7-10 days. Ideal for bulking cycles, lean mass protocols, and TRT support.',
    price: 93.90,
    compare_at_price: null,
    sku: 'TE-300-10ML',
    stock_quantity: 50,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-2',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2022/03/kamagra-effervescent-100mg-tablets-1-500x500-1-300x300.webp',
    images: [{ id: 'img-1', product_id: 'prod-1', url: 'https://steroids-uk.com/wp-content/uploads/2024/09/testosterone-gel-500x500-1.webp', position: 0, is_primary: true }],
    tags: ['testosterone', 'injectable', 'bulking'],
    rating: 4.8,
    review_count: 214,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Anavar10 ΓÇô Pharmaqo Labs [10mg/100tabs]',
    slug: 'anavar-10mg-tablets',
    short_description: 'Oxandrolone 10mg ┬╖ 100 tablets per pack.',
    description: 'Premium oral oxandrolone formulation. Excellent for lean muscle preservation and strength gains with minimal side effects.',
    price: 103.90,
    compare_at_price: null,
    sku: 'AVAR-10-100',
    stock_quantity: 35,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-1',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2017/11/Super-Kamagra-300x300.webp',
    images: [{ id: 'img-2', product_id: 'prod-2', url: 'https://steroids-uk.com/wp-content/uploads/2021/12/anastrazol-neola-front.webp', position: 0, is_primary: true }],
    tags: ['oral', 'cutting', 'lean mass'],
    rating: 4.9,
    review_count: 189,
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Clenbuterol ΓÇô Pharmaqo Labs [100Tabs/40mcg]',
    slug: 'clenbuterol-40mcg',
    short_description: 'Thermogenic bronchodilator. 40mcg ┬╖ 100 tablets.',
    description: 'High-purity clenbuterol hydrochloride for advanced thermogenic protocols. Each tablet contains 40mcg of active compound for precise dosing.',
    price: 103.90,
    compare_at_price: null,
    sku: 'CLEN-40-100',
    stock_quantity: 80,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-3',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2026/01/cialis-300x300.webp',
    images: [{ id: 'img-3', product_id: 'prod-3', url: 'https://steroids-uk.com/wp-content/uploads/2024/10/liv-52-himalaya-700x700.webp', position: 0, is_primary: true }],
    tags: ['fat burner', 'thermogenic', 'cutting'],
    rating: 4.7,
    review_count: 156,
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Testosterone-C 200 ΓÇô Pharmaqo Labs',
    slug: 'testosterone-cypionate-200',
    short_description: 'Slow-release testosterone. 200mg/ml ┬╖ 10ml vial.',
    description: 'Testosterone Cypionate offers a slightly longer half-life than enanthate, perfect for stable blood levels in TRT and performance protocols.',
    price: 107.90,
    compare_at_price: null,
    sku: 'TC-200-10ML',
    stock_quantity: 45,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-2',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2025/11/prilimed-30_blister-300x300.webp',
    images: [{ id: 'img-4', product_id: 'prod-4', url: 'https://steroids-uk.com/wp-content/uploads/2015/11/terpafen-clomifenec-citrate-50-mg-500x500-1.webp', position: 0, is_primary: true }],
    tags: ['testosterone', 'injectable', 'trt'],
    rating: 4.8,
    review_count: 98,
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Dianabol ΓÇô Pharmaqo Labs [100tabs/10mg]',
    slug: 'dianabol-10mg',
    short_description: 'Classic mass builder. 10mg ┬╖ 100 tablets.',
    description: 'One of the most well-known oral anabolic compounds. Dianabol 10mg offers rapid strength and mass gains when used as part of a structured bulking protocol.',
    price: 107.90,
    compare_at_price: null,
    sku: 'DBOL-10-100',
    stock_quantity: 60,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-1',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2023/01/b-lgd-4033-ligandrol-pharmaqo-300x300.webp',
    images: [{ id: 'img-5', product_id: 'prod-5', url: 'https://steroids-uk.com/wp-content/uploads/2020/08/imusclesarmsuk-ibutamorenmk677_1024x1024@2x-700x700.webp', position: 0, is_primary: true }],
    tags: ['oral', 'bulking', 'mass'],
    rating: 4.6,
    review_count: 201,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Anavar 50 ΓÇô Pharmaqo Labs [50mg/50tabs]',
    slug: 'anavar-50mg-tablets',
    short_description: 'High-dose oxandrolone. 50mg ┬╖ 50 tablets.',
    description: 'Premium high-dose Anavar formulation for advanced athletes seeking superior strength and body recomposition.',
    price: 90.00,
    compare_at_price: 105.00,
    sku: 'AVAR-50-50',
    stock_quantity: 20,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-1',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2020/08/imusclesarmsuk-ligandrollgd4033_1024x1024@2x-1-300x300.webp',
    images: [{ id: 'img-6', product_id: 'prod-6', url: 'https://steroids-uk.com/wp-content/uploads/2020/08/imusclesarmsuk-cardarinegw501516_1024x1024@2x-700x700.webp', position: 0, is_primary: true }],
    tags: ['oral', 'cutting', 'advanced'],
    rating: 4.9,
    review_count: 87,
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2024-01-06T00:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'Clenbuterol ΓÇô Proper Labs [100Tabs/40mcg]',
    slug: 'clenbuterol-proper-labs',
    short_description: 'Premium thermogenic. 40mcg ┬╖ 100 tablets.',
    description: 'Proper Labs premium clenbuterol with enhanced purity standards and tight dosing accuracy.',
    price: 93.90,
    compare_at_price: 101.90,
    sku: 'PL-CLEN-40-100',
    stock_quantity: 60,
    in_stock: true,
    is_featured: false,
    is_on_sale: true,
    category_id: 'cat-3',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2024/05/Proscalpin-1-agm22mL-150x150.webp',
    images: [{ id: 'img-7', product_id: 'prod-7', url: 'https://steroids-uk.com/wp-content/uploads/2020/08/S-23_1024x1024@2x-700x700.webp', position: 0, is_primary: true }],
    tags: ['fat burner', 'sale', 'proper labs'],
    rating: 4.7,
    review_count: 73,
    created_at: '2024-01-07T00:00:00Z',
    updated_at: '2024-01-07T00:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'Supersus 400 ΓÇô Pharmaqo Labs',
    slug: 'supersus-400-blend',
    short_description: 'Multi-ester testosterone blend. 400mg/ml ┬╖ 10ml vial.',
    description: 'A powerful multi-ester testosterone blend delivering both fast-acting and sustained release.',
    price: 95.90,
    compare_at_price: null,
    sku: 'SSUS-400-10ML',
    stock_quantity: 30,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-2',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2024/02/finax_1mg_tablet_30s_35081_0_1-300x300.webp',
    images: [{ id: 'img-8', product_id: 'prod-8', url: 'https://steroids-uk.com/wp-content/uploads/2022/03/kamagra-effervescent-100mg-tablets-1-500x500-1-300x300.webp', position: 0, is_primary: true }],
    tags: ['testosterone', 'blend', 'injectable'],
    rating: 4.7,
    review_count: 61,
    created_at: '2024-01-08T00:00:00Z',
    updated_at: '2024-01-08T00:00:00Z',
  },
  {
    id: 'prod-9',
    name: 'Tamoxifen / Nolvadex ΓÇô Pharmaqo Labs [50tab/20mg]',
    slug: 'nolvadex-tamoxifen-20mg',
    short_description: 'SERM for PCT. 20mg ┬╖ 50 tablets.',
    description: 'Tamoxifen citrate is the gold-standard SERM for post-cycle therapy. Helps restore natural testosterone production.',
    price: 105.90,
    compare_at_price: null,
    sku: 'NOLVA-20-50',
    stock_quantity: 55,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-5',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2024/09/testosterone-gel-500x500-1.webp',
    images: [{ id: 'img-9', product_id: 'prod-9', url: 'https://steroids-uk.com/wp-content/uploads/2017/11/Super-Kamagra-300x300.webp', position: 0, is_primary: true }],
    tags: ['pct', 'serm', 'oral'],
    rating: 4.8,
    review_count: 142,
    created_at: '2024-01-09T00:00:00Z',
    updated_at: '2024-01-09T00:00:00Z',
  },
  {
    id: 'prod-10',
    name: 'HCG 5000IU ΓÇô Pharmaqo Labs',
    slug: 'hcg-5000iu',
    short_description: 'Human Chorionic Gonadotropin. 5000IU kit.',
    description: 'Pharmaceutical-grade HCG for testicular function restoration during and after steroid cycles.',
    price: 105.90,
    compare_at_price: null,
    sku: 'HCG-5000IU',
    stock_quantity: 25,
    in_stock: true,
    is_featured: false,
    is_on_sale: false,
    category_id: 'cat-5',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2021/12/anastrazol-neola-front.webp',
    images: [{ id: 'img-10', product_id: 'prod-10', url: 'https://steroids-uk.com/wp-content/uploads/2026/01/cialis-300x300.webp', position: 0, is_primary: true }],
    tags: ['pct', 'hcg', 'injectable'],
    rating: 4.9,
    review_count: 78,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'prod-11',
    name: 'Kamagra Gold',
    slug: 'kamagra-gold-100mg',
    short_description: 'Sildenafil citrate. 100mg ┬╖ 4 tablets.',
    description: 'Premium sildenafil citrate formulation for male sexual health and performance.',
    price: 100.90,
    compare_at_price: 94.90,
    sku: 'KAMA-100-4',
    stock_quantity: 100,
    in_stock: true,
    is_featured: false,
    is_on_sale: true,
    category_id: 'cat-8',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2024/10/liv-52-himalaya-700x700.webp',
    images: [{ id: 'img-11', product_id: 'prod-11', url: 'https://steroids-uk.com/wp-content/uploads/2025/11/prilimed-30_blister-300x300.webp', position: 0, is_primary: true }],
    tags: ['sexual wellness', 'sale'],
    rating: 4.5,
    review_count: 229,
    created_at: '2024-01-11T00:00:00Z',
    updated_at: '2024-01-11T00:00:00Z',
  },
  {
    id: 'prod-12',
    name: 'Anadrol 50 ΓÇô Pharmaqo Labs [60tabs/50mg]',
    slug: 'anadrol-50mg',
    short_description: 'Oxymetholone 50mg ┬╖ 60 tablets.',
    description: 'Powerful oral mass builder. Anadrol 50mg is among the most potent oral anabolics for rapid strength and size gains.',
    price: 95.90,
    compare_at_price: null,
    sku: 'ADROL-50-60',
    stock_quantity: 40,
    in_stock: true,
    is_featured: false,
    is_on_sale: false,
    category_id: 'cat-1',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2015/11/terpafen-clomifenec-citrate-50-mg-500x500-1.webp',
    images: [{ id: 'img-12', product_id: 'prod-12', url: 'https://steroids-uk.com/wp-content/uploads/2023/01/b-lgd-4033-ligandrol-pharmaqo-300x300.webp', position: 0, is_primary: true }],
    tags: ['oral', 'bulking', 'mass', 'advanced'],
    rating: 4.7,
    review_count: 110,
    created_at: '2024-01-12T00:00:00Z',
    updated_at: '2024-01-12T00:00:00Z',
  },
  {
    id: 'prod-13',
    name: 'Ostarine MK-2866 25mg',
    slug: 'ostarine-mk-2866-25mg',
    short_description: 'Beginner-friendly SARM. 25mg ┬╖ 60 capsules.',
    description: 'Ostarine is the most well-researched SARM, ideal for lean muscle gain and fat loss simultaneously.',
    price: 100.90,
    compare_at_price: null,
    sku: 'OST-25-60',
    stock_quantity: 40,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-4',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2020/08/imusclesarmsuk-ibutamorenmk677_1024x1024@2x-700x700.webp',
    images: [{ id: 'img-13', product_id: 'prod-13', url: 'https://steroids-uk.com/wp-content/uploads/2020/08/imusclesarmsuk-ligandrollgd4033_1024x1024@2x-1-300x300.webp', position: 0, is_primary: true }],
    tags: ['sarms', 'recomp', 'beginner'],
    rating: 4.8,
    review_count: 134,
    created_at: '2024-01-13T00:00:00Z',
    updated_at: '2024-01-13T00:00:00Z',
  },
  {
    id: 'prod-14',
    name: 'RAD-140 Testolone 10mg',
    slug: 'rad-140-testolone-10mg',
    short_description: 'Potent anabolic SARM. 10mg ┬╖ 60 capsules.',
    description: 'RAD-140 is one of the most potent SARMs with an impressive anabolic-to-androgenic ratio.',
    price: 109.90,
    compare_at_price: null,
    sku: 'RAD-10-60',
    stock_quantity: 28,
    in_stock: true,
    is_featured: true,
    is_on_sale: false,
    category_id: 'cat-4',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2020/08/imusclesarmsuk-cardarinegw501516_1024x1024@2x-700x700.webp',
    images: [{ id: 'img-14', product_id: 'prod-14', url: 'https://steroids-uk.com/wp-content/uploads/2024/05/Proscalpin-1-agm22mL-150x150.webp', position: 0, is_primary: true }],
    tags: ['sarms', 'bulking', 'advanced'],
    rating: 4.9,
    review_count: 89,
    created_at: '2024-01-14T00:00:00Z',
    updated_at: '2024-01-14T00:00:00Z',
  },
  {
    id: 'prod-15',
    name: 'Cardarine GW-501516 10mg',
    slug: 'cardarine-gw-501516-10mg',
    short_description: 'Endurance & fat loss SARM. 10mg ┬╖ 60 capsules.',
    description: 'Cardarine enhances endurance, promotes fat oxidation, and improves metabolic efficiency.',
    price: 106.90,
    compare_at_price: null,
    sku: 'CARD-10-60',
    stock_quantity: 32,
    in_stock: true,
    is_featured: false,
    is_on_sale: false,
    category_id: 'cat-4',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2020/08/S-23_1024x1024@2x-700x700.webp',
    images: [{ id: 'img-15', product_id: 'prod-15', url: 'https://steroids-uk.com/wp-content/uploads/2024/02/finax_1mg_tablet_30s_35081_0_1-300x300.webp', position: 0, is_primary: true }],
    tags: ['sarms', 'cutting', 'endurance'],
    rating: 4.7,
    review_count: 112,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'prod-16',
    name: 'Bulking Stack ΓÇô Pro Series',
    slug: 'bulking-stack-pro-series',
    short_description: 'Complete bulking protocol bundle. Best value.',
    description: 'Expert-curated bulking stack with testosterone base, oral kickstart, and full PCT.',
    price: 149.90,
    compare_at_price: 189.90,
    sku: 'STACK-BULK-PRO',
    stock_quantity: 15,
    in_stock: true,
    is_featured: true,
    is_on_sale: true,
    category_id: 'cat-7',
    primary_image: 'https://steroids-uk.com/wp-content/uploads/2022/03/kamagra-effervescent-100mg-tablets-1-500x500-1-300x300.webp',
    images: [{ id: 'img-16', product_id: 'prod-16', url: 'https://steroids-uk.com/wp-content/uploads/2024/09/testosterone-gel-500x500-1.webp', position: 0, is_primary: true }],
    tags: ['stack', 'bundle', 'bulking', 'featured'],
    rating: 4.9,
    review_count: 67,
    created_at: '2024-01-16T00:00:00Z',
    updated_at: '2024-01-16T00:00:00Z',
  },
]

// ΓöÇΓöÇΓöÇ Blog Posts ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export const blogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'The Complete Guide to Bulking and Cutting Cycles',
    slug: 'complete-guide-bulking-cutting-cycles',
    excerpt: 'Understanding the fundamentals of bulking and cutting is essential for any serious athlete. Learn how to structure your cycles for maximum results with minimal risk.',
    content: `# The Complete Guide to Bulking and Cutting Cycles\n\nFor any serious athlete or bodybuilder, understanding how to structure anabolic cycles is fundamental to achieving your physique goals safely and effectively.\n\n## What is a Bulking Cycle?\n\nA bulking cycle focuses on maximising muscle mass gain over a defined period. During this phase, athletes typically run a caloric surplus alongside anabolic compounds that enhance protein synthesis and nitrogen retention in muscle tissue.\n\n### Key Principles of Bulking\n\n1. **Caloric Surplus** ΓÇö Consuming more calories than you burn\n2. **Progressive Overload** ΓÇö Consistently increasing training volume and intensity\n3. **Recovery Priority** ΓÇö Adequate sleep and rest periods\n4. **Compound Selection** ΓÇö Choosing appropriate anabolics for mass gain\n\n## What is a Cutting Cycle?\n\nA cutting cycle aims to shed body fat while preserving lean muscle mass. This requires a caloric deficit combined with compounds that support fat metabolism and anti-catabolic properties.\n\n## Post-Cycle Therapy\n\nAfter any cycle, restoring your body's natural hormonal balance is essential. PCT protocols typically involve SERMs and other support compounds over 4ΓÇô6 weeks.`,
    cover_image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
    category: 'Training Guides',
    tags: ['bulking', 'cutting', 'cycles', 'guide'],
    published: true,
    published_at: '2026-05-07T00:00:00Z',
    created_at: '2026-05-07T00:00:00Z',
  },
  {
    id: 'blog-2',
    title: 'Understanding Post Cycle Therapy: A Complete Protocol',
    slug: 'understanding-post-cycle-therapy-protocol',
    excerpt: 'Post cycle therapy is one of the most critical aspects of responsible compound use. Here is everything you need to know about running an effective PCT protocol.',
    content: `# Understanding Post Cycle Therapy\n\nPCT is arguably the most important phase of any anabolic compound protocol. Failing to run proper PCT can result in prolonged hormonal suppression and related health issues.\n\n## Why PCT Matters\n\nAnabolic compounds suppress the body's natural testosterone production through the HPG axis feedback loop. PCT uses specific compounds to stimulate LH and FSH release from the pituitary, which in turn signals the testes to resume testosterone production.\n\n## Standard PCT Protocol\n\n- **SERMs** (Tamoxifen, Clomiphene) ΓÇö Primary PCT agents\n- **HCG** ΓÇö Used on-cycle or immediately pre-PCT to maintain testicular volume\n- **Ancillaries** ΓÇö Vitamins, minerals, and liver support compounds\n\n## PCT Timeline\n\nPCT should begin after the last compound has cleared your system. Timing depends on the esters used in your cycle.`,
    cover_image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80',
    category: 'PCT Guide',
    tags: ['pct', 'recovery', 'hormones'],
    published: true,
    published_at: '2026-05-05T00:00:00Z',
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: 'blog-3',
    title: 'SARMs vs Steroids: Key Differences Explained',
    slug: 'sarms-vs-steroids-key-differences',
    excerpt: 'Both SARMs and traditional anabolic steroids are used for muscle building and performance enhancement, but they work very differently. Here is a clear comparison.',
    content: `# SARMs vs Steroids: Key Differences Explained\n\nBoth SARMs (Selective Androgen Receptor Modulators) and traditional anabolic steroids interact with androgen receptors to promote muscle growth, but their mechanisms and side effect profiles differ significantly.\n\n## How Traditional Steroids Work\n\nAnabolic-androgenic steroids bind to androgen receptors throughout the body ΓÇö not just in muscle tissue. This systemic binding is what causes both the desired anabolic effects and the androgenic side effects.\n\n## How SARMs Work\n\nSARMs are designed to selectively target androgen receptors in muscle and bone tissue while minimising activity in other tissues like the prostate and skin.\n\n## Key Comparisons\n\n| Factor | Steroids | SARMs |\n|--------|----------|-------|\n| Anabolic potency | Very high | Moderate-high |\n| Suppression | Significant | Mild-moderate |\n| Research history | Extensive | Limited |\n| Administration | Oral/injectable | Oral |\n\n## Which Is Right For You?\n\nThe choice depends on your experience level, goals, and risk tolerance. Beginners often start with SARMs before progressing to traditional anabolics.`,
    cover_image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800&q=80',
    category: 'Education',
    tags: ['sarms', 'steroids', 'comparison', 'education'],
    published: true,
    published_at: '2026-05-04T00:00:00Z',
    created_at: '2026-05-04T00:00:00Z',
  },
]

// ΓöÇΓöÇΓöÇ FAQs ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export const faqs = [
  {
    id: 'faq-1',
    category: 'Ordering & Payment',
    question: 'What payment methods do you accept?',
    answer: 'We accept bank transfers, cryptocurrency (Bitcoin, Ethereum, USDT), and Revolut payments. Pay with Revolut to receive a 5% discount and a free product with your order.',
  },
  {
    id: 'faq-2',
    category: 'Ordering & Payment',
    question: 'Is my order and payment information secure?',
    answer: 'Yes. All transactions are processed through encrypted channels. We do not store card details and our checkout process uses bank-grade SSL encryption.',
  },
  {
    id: 'faq-3',
    category: 'Delivery',
    question: 'How fast is delivery?',
    answer: 'Standard delivery is 1ΓÇô3 business days. Orders placed before 2PM on a weekday with next-day delivery selected will typically arrive the following business day. Orders of ┬ú149+ qualify for free next-day delivery with code DELIVERY5.',
  },
  {
    id: 'faq-4',
    category: 'Delivery',
    question: 'How is my order packaged?',
    answer: 'All orders are shipped in plain, unmarked packaging with no external indication of contents. Return address is listed as a generic fulfilment address for complete discretion.',
  },
  {
    id: 'faq-5',
    category: 'Products',
    question: 'Are your products laboratory tested?',
    answer: 'Yes. We maintain a library of third-party laboratory test results for our stocked products. You can view lab reports on individual product pages or in our Lab Tests section.',
  },
  {
    id: 'faq-6',
    category: 'Products',
    question: 'Do you guarantee product authenticity?',
    answer: 'We source directly from verified manufacturers and authorised distributors only. Every batch is verified before being added to stock. We do not sell counterfeit or underground lab products.',
  },
  {
    id: 'faq-7',
    category: 'Account',
    question: 'Do I need an account to order?',
    answer: 'Guest checkout is available for most payment methods. However, creating an account allows you to track orders, save addresses, manage your wishlist, and access order history.',
  },
  {
    id: 'faq-8',
    category: 'Account',
    question: 'How do I track my order?',
    answer: 'Once your order ships, you will receive an email with tracking information. You can also log into your account and view the Orders section for real-time status updates.',
  },
  {
    id: 'faq-9',
    category: 'Returns & Refunds',
    question: 'What is your returns policy?',
    answer: 'We accept returns on sealed, unopened products within 14 days of delivery if the product is damaged or incorrect. Please contact our support team with your order number and photos of the issue.',
  },
  {
    id: 'faq-10',
    category: 'Returns & Refunds',
    question: 'What if my order arrives damaged?',
    answer: 'In the rare event of a damaged delivery, please contact us within 48 hours with photographic evidence. We will arrange a replacement or refund at no additional cost.',
  },
]

// ΓöÇΓöÇΓöÇ Navigation ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export const navigationItems = [
  {
    label: 'All Products',
    href: '/shop',
  },
  {
    label: 'Manufacturers',
    href: '/shop/manufacturers',
    children: [
      { label: 'Apex Labs', href: '/shop/manufacturers/apex-labs' },
      { label: 'Precision Pharma', href: '/shop/manufacturers/precision-pharma' },
      { label: 'Synergy Bio', href: '/shop/manufacturers/synergy-bio' },
      { label: 'Elite Research', href: '/shop/manufacturers/elite-research' },
      { label: 'Nova Compounds', href: '/shop/manufacturers/nova-compounds' },
    ],
  },
  {
    label: 'Oral Compounds',
    href: '/shop/oral-compounds',
    children: [
      { label: 'Strength Tablets', href: '/shop/oral-compounds/strength-tablets' },
      { label: 'Lean Mass Oral', href: '/shop/oral-compounds/lean-mass-oral' },
      { label: 'PCT Tablets', href: '/shop/oral-compounds/pct-tablets' },
      { label: 'All Oral Compounds', href: '/shop/oral-compounds' },
    ],
  },
  {
    label: 'Injectable Solutions',
    href: '/shop/injectable-solutions',
    children: [
      { label: 'Testosterone Enanthate', href: '/shop/injectable-solutions/test-enanthate' },
      { label: 'Testosterone Cypionate', href: '/shop/injectable-solutions/test-cypionate' },
      { label: 'Tren Series', href: '/shop/injectable-solutions/tren-series' },
      { label: 'Deca & NPP', href: '/shop/injectable-solutions/deca-npp' },
      { label: 'All Injectables', href: '/shop/injectable-solutions' },
    ],
  },
  {
    label: 'Fat Burners',
    href: '/shop/fat-burners',
    children: [
      { label: 'Thermogenics', href: '/shop/fat-burners/thermogenics' },
      { label: 'Metabolic Support', href: '/shop/fat-burners/metabolic-support' },
      { label: 'GLP-1 Peptides', href: '/shop/fat-burners/glp1-peptides' },
      { label: 'All Fat Burners', href: '/shop/fat-burners' },
    ],
  },
  {
    label: 'SARMs',
    href: '/shop/sarms',
    children: [
      { label: 'Bulking SARMs', href: '/shop/sarms/bulking-sarms' },
      { label: 'Cutting SARMs', href: '/shop/sarms/cutting-sarms' },
      { label: 'Recomp SARMs', href: '/shop/sarms/recomp-sarms' },
      { label: 'SARMs Stacks', href: '/shop/sarms/sarms-stacks' },
      { label: 'All SARMs', href: '/shop/sarms' },
    ],
  },
  {
    label: 'More',
    href: '#',
    children: [
      { label: 'PCT & Support', href: '/shop/pct-support' },
      { label: 'HGH & Peptides', href: '/shop/hgh-peptides' },
      { label: 'Pre-Made Stacks', href: '/shop/pre-made-stacks' },
      { label: 'Sexual Wellness', href: '/shop/sexual-wellness' },
      { label: 'Best for Bulking', href: '/shop?goal=bulking' },
      { label: 'Best for Cutting', href: '/shop?goal=cutting' },
    ],
  },
  {
    label: 'Resources',
    href: '#',
    children: [
      { label: 'Blog', href: '/blog' },
      { label: 'FAQ', href: '/faq' },
      { label: 'Delivery Info', href: '/shipping' },
      { label: 'Payment Info', href: '/payments' },
      { label: 'Contact Us', href: '/contact' },
    ],
  },
]

// ΓöÇΓöÇΓöÇ Promo Strip ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

export const promoMessages = [
  'Pay with Revolut: Receive FREE product + 5% discount ΓÇö Code: REVO10',
  'Free Next-Day Delivery on orders ┬ú149+ ΓÇö Code: DELIVERY5',
  'All products independently lab tested for purity and accuracy',
  'Discreet plain packaging ΓÇö no external branding',
  '1,000+ products in stock ΓÇö Same day dispatch before 2PM',
]
